### ISSUE TITLE
Consul connect injected sidecars not permitted by Pod Security Policies

### ISSUE THREAD

**Issue by barrymars** [hashicorp/consul-helm#1044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I have a new Consul deployment on Kubernetes, where I have had to enable PSPs via the helm chart because we have global PSPs to restrict privileged pods:
Consul: 1.10.0
Helm Chart: 0.32.0
Kubernetes: 1.19 (EKS)

All of the cluster components come up just fine, but when I try to deploy a service with the connect-inject annotation, the init-containers injected by consul-connect are failing to start (to be admitted) with the following error
```
Error creating: pods "static-client-7d5974457f-" is forbidden: PodSecurityPolicy: unable to admit pod: 
[spec.initContainers[1].securityContext.runAsNonRoot: Invalid value: false: must be true 
spec.initContainers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed 
spec.initContainers[1].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added]
```

Should there be a PSP that these containers use to allow them to run?
Os is there a way to set the securityContext of the containers?

**Comment by ishustava** [comment]
Hey @barrymars 

This is expected. As of consul-helm 0.32.0, we're running the Consul service mesh in transparent proxy mode by default. This means that each pod will have iptables rules set up so that all traffic is forwarded to the sidecar proxy. This also means that you can now just use kubeDNS to access your upstream services within a Kubernetes cluster instead of `localhost`.

To enable the transparent proxy feature, we run an init container that sets up those iptables rules, and to run iptables commands we need those privileges.

If you want to run with tproxy, then you'd need to update the pod security policies on your cluster to allow the init container to have those privileges.

If you don't want the tproxy feature, you can disable that for the whole cluster via the `connectInject.transparentProxy.defaultEnable` helm chart value, and those errors will go away. [Here](https://www.consul.io/docs/connect/transparent-proxy#configuration) is some more info on how to enable and migrate to tproxy if you're interested.

**Comment by barrymars** [comment]
@ishustava Thank you, that makes perfect sense.

Had read bits about the transparent proxy, but hadn't realised it was enabled by default now.
