### ISSUE TITLE
Priority class for Consul server

### ISSUE THREAD

**Issue by djanjic** [hashicorp/consul-helm#116]
Hi, I cannot find a way to set `priorityClassName` property. Can you include this or point in the documentation how to do this?

**Comment by adilyse** [comment]
Hi @djanjic,

We merged the `priorityClassName` functionality for servers and clients with #92, but it looks like we missed adding the documentation at that point. I've opened a [PR](https://github.com/hashicorp/consul/pull/5444) to add this to the main Helm chart documentation. Thank you for letting us know!

I'm going to close this now, since the documentation PR will be merged shortly, but please feel free to comment or open another issue if there is anything I've missed.
