### ISSUE TITLE
Consul agent registers node with the name of the pod

### ISSUE THREAD

**Issue by mmisztal1980** [hashicorp/consul-helm#14]
When starting agent instances, the agents use the hostnames of the pods **consul-{random}** to register as nodes. IMHO this isn't desired and creates confusion for the operator of the consul cluster, b/c it's impossible to tell which node represents which physical k8s node.

**Comment by mmisztal1980** [comment]
@mitchellh please have a look if my issue is valid and the proposed solution is satisfactory.
Best regards

**Comment by mmisztal1980** [comment]
@mitchellh did you guys get a chance to review the PR?

**Comment by mitchellh** [comment]
We're going to take a look soon. I just want to verify that this doesn't cause any issues with the server agents since they run alongside the client agents in K8S (due to daemonsets not respecting affinities). I don't think so since I think they set their node name to something else, but just want to be sure!
