### ISSUE TITLE
Steps for ACL initialization

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-helm#180]
My current ACL initialization flow:
- spin up a Consul cluster with a master token
  - master token provided via server extraVolume w/ type: "secret" and load: true
- run a helm/k8s job to create new ACL policies & issue ACL tokens for each 
  - required because the cluster is intentionally never being exposed to the internet
- scrape the job logs for those tokens
- save custom acl token for later use (Vault in this case)
- update Consul server secret extraVolume with new server acl token
- restart Consul pod to use the updated extraVolume

This is a very lengthy process with multiple steps that can go wrong.
I'd like to hear ideas as to how to improve this process or features we can add to the helm chart to improve it.
The only ideas I've had revolve around adding extra ACL bootstrapping and policy+token creation logic to the Consul server instances but that brings with it issues of secure storage of those tokens.

**Comment by adilyse** [comment]
Hi @infa-bsurber,

In the latest release (Consul v1.5, consul-k8s v0.8.1 and consul-helm v0.8.1), we've added the ability to automatically bootstrap ACLs in a Consul cluster that's running completely in Kubernetes. By turning on the [`bootstrapACLs`](https://www.consul.io/docs/platform/k8s/helm.html#v-global-bootstrap-acls) option in the Helm chart, ACLs will be automatically turned on and tokens created and passed out to the various components on startup. The tokens are automatically stored in Kubernetes secrets, so it's possible to extract the bootstrapping token so you can create any additional tokens you may need. Overall, this should make it much easier to use ACLs in Kubernetes!

We're working on writing up some better documentation about the new feature so that it will be more discoverable in the future!

**Comment by infa-bsurber** [comment]
Wonderful! Thank you.

**Comment by cristhianbicca** [comment]
Good morning guys, I'm deploying consul as a service discovery on my Kubernetes framework and trying to enable ACL he's asking for a SecretID or Master Token, but what I got from Kubernetes Secret didn't work out. Where can I get this token?

versions
Consul server - 1.5.0
consul-helm 0.9

**Comment by lkysow** [comment]
Hi @cristhianbicca, I've moved your question to a new issue.

**Comment by cristhianbicca** [comment]
Thanks @lkysow
