### ISSUE TITLE
bootstrapACLs requires enabling consul clients

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-helm#183]
bootstrapACLs currently requires that clients & servers both be active

We use this chart to deployment multiple consul clusters per k8s cluster, so we disable consul client creation. 

We would appreciate removing the requirement that the clients must be active to use bootstrapACLs.

**Comment by devlounge** [comment]
Same here

**Comment by rosteroster** [comment]
PR updated to use 0.9.0's new bootstrap acl job flag "-create-client-token=false" to disable creating the client acl token when only the server is enabled

**Comment by HansK-p** [comment]
I removed the requirement from consul-helm/templates/server-acl-init-* in a local copy of the chart and it seems that the ACL bootstrap process worked as it should after this change. There is a secret "consul-k8s-consul-client-acl-token" in the namespace which probably shouldn't have been there, but that's not a big problem for us (and we can choose to simply remove it).

I'd appreciate a change in this behavior so that we don't have to use a locally modified helm chart to make ACLs work when we need to host two or more Consul clusters in a K8s cluster (I actually considered enabling clients, but with a label selector which would have prevented the installation, but I haven't tested such an option).

**Comment by rosteroster** [comment]
Yep, #190 is already open to resolve this, it's just not merged yet

**Comment by lkysow** [comment]
Closed by #250
