### ISSUE TITLE
No pods ever gets ready

### ISSUE THREAD

**Issue by ryhled** [hashicorp/consul-helm#195]
Hi!
Trying out consul (on AKS) and it seems i cannot get this to work (install using 'helm install ./ --namespace consul --name consul').

The installer goes through but no pods ever becomes ready. Runs in a two node cluster and the result looks like below:

![image](https://user-images.githubusercontent.com/5057569/59561559-35f44700-9022-11e9-9058-b7256a816c9f.png)

Looking at the logs what frequently reccurs are errors like 'no such host' and 'failed to sync remote state: No cluster leader'.

Is there something i miss that is needed to get this working?

**Comment by ryhled** [comment]
will investigate this further before i reach out. But seems that the telm standard charts work fine 'out of box' to install, but this chart does not.

**Comment by lkysow** [comment]
Hi Daniel, just so you know, this chart is the officially supported HashiCorp chart.

**Comment by ryhled** [comment]
Yeah i understood that. However it does not work at all for me 'out-of-box'. [this chart](https://github.com/helm/charts/tree/master/stable/consul) however seems to work fine.

**Comment by lkysow** [comment]
To help debug can you do a `describe` on the failing pods?

**Comment by tradel** [comment]
Hi @ryhled. The problem is that our Helm chart defaults to installing 3 server pods with host anti-affinity, and you're running in a cluster with only 2 hosts. The leader is expecting 3 servers to come up and it only 2 pods can ever start.

Try making the following changes to your `values.yaml`:

```yaml
server:
  enabled: "-"
  image: null
  replicas: 2
  bootstrapExpect: 2
```

The values for `server.replicas` and `server.bootstrapExpect` should never be more than the number of hosts in the cluster.

**Comment by ryhled** [comment]
Thanks will try that!

**Comment by ryhled** [comment]
Setting down the nodes and waiting 4-5 minutes helped, works now. Thanks for the input.
