### ISSUE TITLE
helm install error

### ISSUE THREAD

**Issue by mrlesmithjr** [hashicorp/consul-helm#2]
When I do `helm install .` I get the following error:
```bash
Error: parse error in "consul/templates/_helpers.tpl": template: consul/templates/_helpers.tpl:1: function "ceil" not defined
```

Any idea what I am missing?

```bash
helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1+unreleased", GitCommit:"c98726f110e2149ba6780f88bc9a3cff22c37923", GitTreeState:"clean"}
```

Thanks!

**Comment by mitchellh** [comment]
I believe the server is outdated. I'm not sure what the minimum Helm version is since it'd require a version of sprig that includes the `ceil` function. The earliest version of Helm I tried is 2.10. 

If you determine what version of Helm works for you, I'll document it. For now, I'll note 2.10 as a safe minimum.

**Comment by mrlesmithjr** [comment]
Sounds great. I'll do some digging. Thanks!

**Comment by mrlesmithjr** [comment]
Confirmed working using Helm `2.10.0`
