### ISSUE TITLE
Health check fail

### ISSUE THREAD

**Issue by helioaymoto** [hashicorp/consul-helm#245]
Hi,
I have successfully deployed consul on kubernet following the instructions.
I have deployed an application which is registering in Consul and I can confirm checking consul UI, but Consul is actually failing to run the health check.
From the UI I can see the URL which consul is calling for health check, but it seems Consul cannot reach the POD/Service where the application is running...
```
Get http://resttocorba-85b988b999-fqc6d:8080/actuator/health: dial tcp: lookup resttocorba-85b988b999-fqc6d on 10.43.0.10:53: server misbehaving
```
If I connect in the pod and run a curl in the above URL i can see the the UP status:
```
[helio@kub-1 resttocorba]$ kubectl exec -n=consul -it resttocorba-85b988b999-fqc6d /bin/bash
root@resttocorba-85b988b999-fqc6d:/# curl http://resttocorba-85b988b999-fqc6d:8080/actuator/health
{"status":"UP"}root@resttocorba-85b988b999-fqc6d:/#
```
so it seems Consul pod is not able to reach the my application pod... 
Any tips on how to figure out the issue?

Thanks.

**Comment by helioaymoto** [comment]
I have done a workaround in my application which is a java springboot application... I have configured:

```
spring.cloud.consul.discovery.preferIpAddress=true
```
so the application is going to register in consul using IP address instead of hostname... in this way, the consul health check is working fine.
If someone knows what the issue using hostname on this setup then let me know, otherwise I can close this as this solution should be acceptable for me.

Thanks.

**Comment by lkysow** [comment]
Hi @helioaymoto,
Kubernetes DNS can't be used to resolve pod names. From any other Pod, you can't use the pod name (e.g. `curl resttocorba-85b988b999-fqc6d`), instead you need to use the Pod IP.

It only seems like it's working inside your `resttocorba-85b988b999-fqc6d` Pod because there's an `/etc/hosts` entry that maps the pod name (and hostname) to the Pod IP:
```
$ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.32.5.3	my-pod-name <<<<<<<<<<<<<<<<<< see this
```

**Comment by helioaymoto** [comment]
Hi @lkysow ,
Ok, so I think the solution is really to make the application to register into Consul using the IP address, so Consul won't have issue to run the health check.
I got this working making this change in my springboot application configuration.
Thanks for your support.
Best regards.

**Comment by lkysow** [comment]
Yes that will work. Just so you know, we recommend using the Service Sync instead of manually registering Pods yourself via the API. There are a couple of issues with manually registering services:
1. If your Consul Client agent restarts, it will lose its list of registrations unless you can use something like https://github.com/hashicorp/consul-helm/pull/233
1. When your Pod stops running, it needs to manually deregister itself otherwise it will be stay registered (although the health checking will at least mark it as unhealthy).

**Comment by helioaymoto** [comment]
Hi @lkysow,
thanks for pointing issue (1).
So, regarding Service Sync.... are you commenting about: https://www.consul.io/docs/platform/k8s/service-sync.html ?
Just reading and figuring out how it works.
Thanks for all your support.

**Comment by lkysow** [comment]
Yep, that's what I was talking about!

**Comment by abhinav-nath** [comment]
Hi @lkysow, I am using Service Sync to sync my Kubernetes services to consul. So far so good. I am able to sync my NodePort type services and I can see them in the Consul UI. However I see that Consul is not doing the health checks. The health check section is grayed out in the UI. So I am wondering if I could somehow tell Consul to use /actuator/health endpoint on the synced Kubernetes services for doing and passing the health checks ?

**Comment by lkysow** [comment]
Hey Abhinav, health checks aren't supported right now.
