### ISSUE TITLE
Backing and Restoring Consul Snapshot on S3 from Kubernetes

### ISSUE THREAD

**Issue by msidd111** [hashicorp/consul-helm#257]
Can someone provide a instructions creating backup on S3 when Consul is hosted on K8s.

**Comment by msidd111** [comment]
@nseigneur Thanks for providing the strategy. Can you or someone document  step by step implementation of backup and restore strategy.

**Comment by lkysow** [comment]
Hi, this functionality is supported in Consul Enterprise. There was a PR you may look at to add this in open source via a cronjob (https://github.com/hashicorp/consul-helm/pull/345). We didn't merge that PR due to https://github.com/hashicorp/consul-helm/issues/344#issuecomment-608070702 and for the same reasons I don't think we're going to document how to do this unfortunately.
