### ISSUE TITLE
how to set acl.default_policy?

### ISSUE THREAD

**Issue by ado120** [hashicorp/consul-helm#285]
In the helm chart, I've set bootstrapACLs: true. However I would like to set the default_policy to deny which would go in-line with best security practices. Setting 

```
      "acl": {
        "default_policy": "deny"
      } 
```

in server.extraConfig doesn't work and I also get this warning when doing an helm install:

Warning: Defining server extraConfig potentially disrupts the automatic ACL
         bootstrapping required settings. This may cause future issues if
         there are conflicts.

What then would be the best way to set the acl default policy when using the helm chart?

**Comment by ishustava** [comment]
Hi @ado120,

We already set the default deny policy for you when you set `global.bootstrapACLs` to `true` [here](https://github.com/hashicorp/consul-helm/blob/bb4bfa391cd04a8ac16bc4b4f0c006ffbc4d6caa/templates/server-config-configmap.yaml#L16-L26).

**Comment by ado120** [comment]
Thanks Iryna!

Any ideas why when I set bootstrapACLs to true I can still see all the
nodes, k/v and services without inputting the token then?

**Comment by ado120** [comment]
So just to confirm, I've taken off the extraconfigs I put in and only have `global.bootstrapacls` set to true. I do see that the acl json you described is in the configmap `consul-consul-server-config`. However I can still see the nodes, services etc in the UI.. this shouldn't be the case right?

**Comment by ishustava** [comment]
The acl-init job [sets](https://github.com/hashicorp/consul-helm/blob/bb4bfa391cd04a8ac16bc4b4f0c006ffbc4d6caa/templates/server-acl-init-job.yaml#L39-L66) up some tokens for you. It will set the server and client tokens, as well as tokens for sync catalog, connect-inject etc if you've enabled them in your Helm chart. You should be able to see the tokens by running `kubectl get secrets`.

The server gets the global management token, which is why you can see everything in the UI.

Hope this makes sense 😀

**Comment by ishustava** [comment]
@ado120 I have to correct myself there. The UI doesn't have access to the global management token locally.

The real reason you can see services and nodes is because we set the following policy for the anonymous token:
```
node_prefix "" {
   policy = "read"
}
service_prefix "" {
   policy = "read"
}
```
This policy is needed for DNS, more specifically, so that the Kubernetes DNS server can make DNS queries against Consul.

**Comment by ado120** [comment]
Hello @ishustava,

Thank you so much for the clarification. This makes sense now.. so if I create a policy to lock the viewing of nodes, will that mess anything up for dns? Any documentation you can send to me for learning more about server/client tokens? Apologies for all the questions :)

**Comment by lkysow** [comment]
Hi Alexander,
Yes if you change the anonymous token policy to not be able to view nodes then DNS queries will return no nodes.

That being said, are you using Consul DNS in your Kubernetes installation?

**Comment by ishustava** [comment]
Hey @ado120, sorry for the delay.

To add to what Luke said above, if you don't want to use Consul DNS, you could disable it in the chart by setting `dns.enabled` to `false`. This will tell the ACL bootstrapping job not to create a policy for the anonymous token. If you want to use Consul DNS, however, you need this policy.

You could take a look at the [Bootstrapping ACLs guide](https://learn.hashicorp.com/consul/day-0/acl-guide); it has information about policies you'd need for servers, clients, UI, and DNS.

**Comment by adilyse** [comment]
Since it looks like all of the questions have been answered, I'm going to go ahead and close this for now. Please feel free to respond or open another issue if you have any further questions!
