### ISSUE TITLE
tls-init-cleanup-job deletes newly created certificates

### ISSUE THREAD

**Issue by tehmoon** [hashicorp/consul-helm#330]
Hi!

I was looking at the new TLS feature merged couple days ago as it seems to be the only all included TLS option.
I'm running an alternative workflow using helm templates and kustomize, and it's possible that it is not supported.
My issue is that tls-init-cleanup-job runs right after tls-init-job which deletes the newly created certificates. If I delete and run the job again, everything works after.

Not sure how to fix it right away, but I can come up with a patch if necessary.

Also thank you for the hard work for that feature! Looks good so far.

**Comment by tehmoon** [comment]
I think my issue is that it is a `pre-delete` hook but my workflow does not support this.

**Comment by tehmoon** [comment]
I'm closing the issue because I understood how to fix it myself in my workflow.
In order to do it, I have to deactivate generating the hooks and then enable them per use case myself.
If you are curious, this is my kustomize plugin: https://github.com/tehmoon/helm3-chart-inflator

**Comment by ishustava** [comment]
Thanks for posting the solution @tehmoon!

**Comment by chancez** [comment]
It would be useful to be able to configure in your values an option that lets to disable certain helm hooks, like the cleanup hooks. Setting `--no-hooks` is too broad, and not all tools support passing this flag to helm. Right now I'm not sure how I can use this option with argocd since argocd does something like `helm template .. | kubectl apply -f` to create resources and this issue is popping up for me.

**Comment by tehmoon** [comment]
@chancez If argoCD supports kustomize alpha plugins and inflators, you can use your own custom inflator to filter out things you don't want. As an example, I wrote https://github.com/tehmoon/helm3-chart-inflator which does `helm template` internally. But you can use `yq` in yours.
It's kind of a hack but it does fit my workflow pretty nicely.

**Comment by chancez** [comment]
@tehmoon Yeah, I'd rather avoid using custom plugins with kustomize, but I may end up just using a custom config management plugin to deal with this.

**Comment by ishustava** [comment]
Hey all, this chart makes somewhat heavy use of hooks, and many features, including ACLs and TLS, [won't work correctly](https://www.consul.io/docs/k8s/helm#customizing-the-helm-chart) if you disable hooks. We are trying to do our best to balance configurability with ease of use and trying to be very deliberate about adding options that support most use cases. Since Helm hooks are pretty standard in many Helm charts, I think that it's reasonable for us to provide features that make the UX nicer that rely on them.

It also looks like ArgoCD [doesn't support](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks) `pre-delete` hooks. If they will support it at some point in the future, then I could see adding an ability to provide custom annotations for this job, so that it does work in ArgoCD.

Hope this makes sense.

**Comment by chancez** [comment]
> Hey all, this chart makes somewhat heavy use of hooks, and many features, including ACLs and TLS, [won't work correctly](https://www.consul.io/docs/k8s/helm#customizing-the-helm-chart) if you disable hooks. We are trying to do our best to balance configurability with ease of use and trying to be very deliberate about adding options that support most use cases. Since Helm hooks are pretty standard in many Helm charts, I think that it's reasonable for us to provide features that make the UX nicer that rely on them.
> 
> It also looks like ArgoCD [doesn't support](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks) `pre-delete` hooks. If they will support it at some point in the future, then I could see adding an ability to provide custom annotations for this job, so that it does work in ArgoCD.
> 
> Hope this makes sense.

The install hooks are fine, the delete hooks are the real problem. In many cases running the cleanup hooks aren't completely necessary, or can be handled out of band.
