### ISSUE TITLE
bootstrapACL works only with clusters inside the same k8s cluster.

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul-helm#413]
Would be nice to be make bootstrapACL work with servers running outside the same k8s cluster.
Token could be passed via k8s secret as done per CA cert.

**Comment by ishustava** [comment]
Hey @ltagliamonte-dd, thanks for the issue! This is actually something we're currently working on and it's great to hear that there are more use-cases for this out there. 

Just to clarify, are you suggesting that the bootstrap token should be passed in? That is in your case you are bootstrapping servers yourself via the `/acl/bootstrap` API and just want to pass in the bootstrap token so that the rest of the tokens/policies for k8s components are created by the job, correct?

**Comment by ltagliamonte-dd** [comment]
@ishustava yes exactly.
my consul servers runs in a separate environment and i'd love to be able just to pass the client acl token to use.

**Comment by ishustava** [comment]
Great, thanks for this info!

**Comment by dschaaff** [comment]
It'd be great to have native support for this in the chart. My current workaround is to precreate a kubernetes secret with my acl config and mount it as an extra config.

**Comment by ishustava** [comment]
We've released ACL support for external Consul servers in the 0.20.x release. Here are some useful links:

[Release notes](https://github.com/hashicorp/consul-helm/releases/tag/v0.20.0)
[Docs](https://www.consul.io/docs/platform/k8s/servers-outside-kubernetes.html#configuring-acls)

I'm going to close this issue for now, but let us know if you experience any problems with these new features. Thanks!
