### ISSUE TITLE
How to access consul from pod ?

### ISSUE THREAD

**Issue by wenerme** [hashicorp/consul-helm#541]
Installed by

```bash
helm upgrade -i consul hashicorp/consul   -n service \
    --set global.name=consul --set global.datacenter=center \
    --set server.storageClass=longhorn \
    --set connectInject.enabled=true
```

Will install a service `consul-server.service`, should the pod directly access the server's api ? or interact with per-node agent (no such service like consul-agent)? or somehow to use 127.0.0.1:8500 ?

Is there any guide on how to access consul from pod ?

**Comment by adilyse** [comment]
Hi @wenerme,

Can you tell me a little more about why the pod needs to talk to Consul?

It looks like you've turned on Connect sidecar injection (complete documentation on the feature is available [here](https://www.consul.io/docs/k8s/connect/overview)). A Connect sidecar pod will be automatically injected for any deployed pods that include the [annotation](https://www.consul.io/docs/k8s/connect/overview#consul-hashicorp-com-connect-inject) `'consul.hashicorp.com/connect-inject': 'true'`. This injection process automatically registers the pod with the Consul agent running on the Kubernetes node where it's been deployed, so it doesn't need to directly access Consul for registration purposes.

Note: you can automatically inject all pods that are deployed by setting [`connectInject.default=true`](https://www.consul.io/docs/k8s/helm#v-connectinject-default).

**Comment by wenerme** [comment]
@adilyse Thank you for you reply.

I don't want to register pod, instead, I want to register RPC service like

```
me.wener.user.UserService
```

This service point to the k8s service, port 3000 ,with health check, other endpoint need to access consul to get the address, port and some custom metadata like rpc schema.But I don't know which consul I should talk to.

**Comment by lkysow** [comment]
Hi @wenerme,
If the k8s service is running on a single node (i.e. a pod) then you'll want to register with the consul client on that node using the `/agent/service/register` endpoint (https://www.consul.io/api-docs/agent/service#register-service) (consul client is running on host port 8500) so that if that node dies, then the service gets deregistered.

If that's not the case, then you can register with a consul client or a server using the `/catalog/register` endpoint (https://www.consul.io/api-docs/catalog#register-entity). This registration won't be associated with a particular consul client.

**Comment by wenerme** [comment]
@lkysow Thanks, need to read more doc.
