### ISSUE TITLE
Zero downtime upgrade for consul client daemonsets

### ISSUE THREAD

**Issue by andyyaldoo** [hashicorp/consul-helm#567]
Hi,

I was trying to upgrade the consul clients from `1.8.0` to `1.8.1` using the helm chart yesterday and it upgraded successfully. However, during the upgrade, when a service called its upstream, it returned error below:
```
curl: (56) Recv failure: Connection reset by peer
```

Is there a way to avoid this?

**Comment by ishustava** [comment]
Hi @andyyaldoo,

Unfortunately, the Consul clients cannot be upgraded in a rolling fashion because they take up a host port. The best way to avoid this is to update clients one-by-one by cordoning or tainting nodes, draining connect services from there and then restarting clients. 

I think we need to add more documentation on how to properly do that, but here are rough steps:

1. Change the client update strategy to `OnDelete` and run a Helm upgrade. This will not cause any clients to be rolled yet.
    ```yaml
     client:
       updateStrategy: |
         type: OnDelete
   ```
1. Choose a node you want to upgrade. To minimize downtime, I recommend to first cordon or taint the node as unschedulable and then restart all connect services that are running on that node. You could also use `kubectl drain` to evict pods from a node, however, it won't do a rolling deploy for deployments that have a single instance, so you will still see downtime. If that is acceptable to you, then I'd recommend specifying `--pod-selector` to make sure you won't evict consul server pods:
     ```shell
     kubectl drain <node> --pod-selector app!=consul --ignore-daemonsets --delete-local-data
     ```
     Note you would have to make sure you have enough resources on other nodes to schedule those pods.
1. Delete the Consul client pod from that node. If you have tainted the node, you would need to un-taint it first so that the new client pod is created. Uncordon the node if you have cordoned it.
1. Repeat steps 2-3 for other nodes.

**Comment by andyyaldoo** [comment]
I see, thanks for the clarification. Agree that this should be added to the documentation

**Comment by lkysow** [comment]
Closed by https://github.com/hashicorp/consul/pull/8789
