### ISSUE TITLE
Uninstall CRDs on helm uninstall

### ISSUE THREAD

**Issue by david-yu** [hashicorp/consul-helm#646]
After running an uninstall, CRDs still exist and block a new installation of Consul Helm from completing:

```
helm install -f config.yml consulbeta  hashicorp/consul
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: proxydefaults.consul.hashicorp.com, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition
```

**Comment by lkysow** [comment]
This is because the CRDs weren't deleted on uninstall, most likely because there were some custom resources created. We'll look into a way to handle this in Helm. For now you'll need to
1. Find the resources that are hanging around
    ```
    kubectl get servicedefaults # etc
    NAME                     SYNCED
    servicedefaults-sample   True
   ```
1. Patch to remove the finalizer preventing it from being deleted
   ```
   kubectl patch servicedefaults servicedefaults-sample -p '{"metadata":{"finalizers":[]}}' --type=merge
   servicedefaults.consul.hashicorp.com/servicedefaults-sample patched
   ```

Once all the resources of a particular kind have been deleted, the CRD will be deleted and then the re-install will work.


When uninstalling next time, you'll need to delete each custom resource first before running `helm delete`

**Comment by lkysow** [comment]
Closing because this is a limitation of crds.
