### ISSUE TITLE
Docs need updating for CoreDNS

### ISSUE THREAD

**Issue by nfisher** [hashicorp/consul-helm#68]
Will try to make a PR but currently the docs relating to consul-helm here are related to kube-dns:

https://www.consul.io/docs/platform/k8s/dns.html

I believe as of k8s v1.11 CoreDNS is now the standard name server.

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns

Unfortunately it's a completely different syntax for coredns vs kube-dns. :(

**Comment by madsonic** [comment]
i think this part in the docs is related as well. Perhaps stating the kubernetes version that needs to upgrade to `CoreDNS` would be helpful.

**Comment by nfisher** [comment]
Looks like GKE supports v1.11 but has kept kube-dns. Not sure what the other 1st tier cloud providers are doing?

**Comment by DWSR** [comment]
@nfisher CoreDNS is now GA and `kube-dns` has been deprecated per https://github.com/kubernetes/enhancements/issues/566 so it makes sense to update the documentation to at least add instructions for CoreDNS

**Comment by adilyse** [comment]
Adding CoreDNS instructions to the documentation in this [Consul PR](https://github.com/hashicorp/consul/pull/5523). Hopefully that helps clarify the situation for folks running CoreDNS now instead of kube-dns. 

I'm going to close this, but please feel free to comment or open another issue if there is anything missing.
