### ISSUE TITLE
Register out kubernetes

### ISSUE THREAD

**Issue by kolesoffac** [hashicorp/consul-helm#70]
I have _syncCatalog_ is enabled. I registered outside service on node use rest api consul agent.  In kubernetes auto create service(_my-service_) from consul catalog.

How can i access _my-service_ from kubernetes use dns name?

_my-service.default_  return ip pod of consul-agent(daemontset), but my need ip node where run consul-agent.

Thanks

**Comment by lkysow** [comment]
Hi Anatoly,
If you're registering an external service, you should not use `/agent/service/register` endpoint of a node in Kubernetes. The agent endpoint assumes that the service is running on the same node of the agent. If the node goes down, it will assume your service is unhealthy which isn't true since you're not actually running on that node.

If you can, you should run the Consul agent on your external node and register your service with that agent.

If you can't do that, you can use the `/catalog/register` endpoint and create a new node and service with the right IP. Then when this service is synced into Kubernetes it should have the right IP.
