### ISSUE TITLE
Clear service of node when restart pod

### ISSUE THREAD

**Issue by kolesoffac** [hashicorp/consul-helm#72]
I registered out service in consul use rest api consul client(daemonset).  But after restart pod all service is clean of this node, although this service is alive.

Is this right?

**Comment by lkysow** [comment]
Hi Anatoly, can you give us more detail? You manually registered your service and then when your Pod restarted the service was deleted?

Did you try using the catalog sync feature?

**Comment by lkysow** [comment]
I'm guessing this is because the consul agent pod was restarted. It stores its data in a volume that gets deleted when the agent pod restarts. Thus the service would need to be re-registered.

Instead of registering manually, we recommend you use the [service sync](https://www.consul.io/docs/platform/k8s/service-sync.html) feature.

If you must register manually, you could use a hostPath mount (once this PR is merged: https://github.com/hashicorp/consul-helm/pull/233) so that when the Consul agent restarts it will retain its data.

I'm going to close this because its solved either by using service sync or that pull request.
